{{- $repository_url := .Values.repository.url | required ".Values.repository.url is required." -}}
{{- $branch := .Values.repository.branch | required ".Values.repository.branch is required." -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdclusterapps
  namespace: argocd
spec:
  project: base-app-project
  source:
    path: "charts/argocdclusterapps/"
    repoURL: {{ $repository_url }}
    targetRevision: {{ $branch }}
    helm:
      parameters:
      - name: "repository.url"
        value: {{ $repository_url }}
      - name: "repository.branch"
        value: {{ $branch }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

